// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDecision(arg1) {
  return window['go']['main']['App']['AnalyzeDecision'](arg1);
}

export function CalculateFitness(arg1) {
  return window['go']['main']['App']['CalculateFitness'](arg1);
}

export function Evolve() {
  return window['go']['main']['App']['Evolve']();
}

export function ExportDecisionCSV(arg1) {
  return window['go']['main']['App']['ExportDecisionCSV'](arg1);
}

export function ExportDecisionJSON(arg1) {
  return window['go']['main']['App']['ExportDecisionJSON'](arg1);
}

export function GetAllSolutions() {
  return window['go']['main']['App']['GetAllSolutions']();
}

export function GetCatalog() {
  return window['go']['main']['App']['GetCatalog']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDecisionCriteria() {
  return window['go']['main']['App']['GetDecisionCriteria']();
}

export function GetDecisionScenarios() {
  return window['go']['main']['App']['GetDecisionScenarios']();
}

export function GetDiversityMetrics() {
  return window['go']['main']['App']['GetDiversityMetrics']();
}

export function GetOptimalSolutions(arg1) {
  return window['go']['main']['App']['GetOptimalSolutions'](arg1);
}

export function InitPopulation() {
  return window['go']['main']['App']['InitPopulation']();
}

export function SetConstraints(arg1) {
  return window['go']['main']['App']['SetConstraints'](arg1);
}

export function UpdateCatalog(arg1) {
  return window['go']['main']['App']['UpdateCatalog'](arg1);
}

export function UpdateParetoFront() {
  return window['go']['main']['App']['UpdateParetoFront']();
}

export function UpdatePositions(arg1, arg2) {
  return window['go']['main']['App']['UpdatePositions'](arg1, arg2);
}
