// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateFitness(arg1) {
  return window['go']['main']['App']['CalculateFitness'](arg1);
}

export function Evolve() {
  return window['go']['main']['App']['Evolve']();
}

export function GetCatalog() {
  return window['go']['main']['App']['GetCatalog']();
}

export function GetOptimalSolutions(arg1) {
  return window['go']['main']['App']['GetOptimalSolutions'](arg1);
}

export function InitPopulation() {
  return window['go']['main']['App']['InitPopulation']();
}

export function SetConstraints(arg1) {
  return window['go']['main']['App']['SetConstraints'](arg1);
}

export function UpdateCatalog(arg1) {
  return window['go']['main']['App']['UpdateCatalog'](arg1);
}

export function UpdateParetoFront() {
  return window['go']['main']['App']['UpdateParetoFront']();
}

export function UpdatePositions(arg1, arg2) {
  return window['go']['main']['App']['UpdatePositions'](arg1, arg2);
}
