// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalculateFitness(arg1:main.Individual):Promise<void>;

export function Evolve():Promise<Array<main.Individual>>;

export function GetCatalog():Promise<Array<main.Sensor>>;

export function InitPopulation():Promise<void>;

export function SetConstraints(arg1:main.Config):Promise<void>;

export function UpdateCatalog(arg1:Array<main.Sensor>):Promise<void>;

export function UpdateParetoFront():Promise<void>;

export function UpdatePositions(arg1:main.Individual,arg2:Array<main.Sensor>):Promise<void>;
